Accounts/urls.py
from django.urls import path,include
from Accounts import views

app_name="Accounts"
urlpatterns = [
    path("login/",views.Login,name="login"),
    path("HospitalRegistration/",views.RegisterHospital,name="HospitalSignup"),
    path("Ajax_load_place/",views.AjaxPalce,name="AjaxPlaces"),
    path("UserRegistration/",views.RegisterUser,name="UserSignup"),
    path("Registration/",views.Registration,name="Registration")
]


# Accounts URLS

# http://127.0.0.1:8000/accounts/Registration/

# http://127.0.0.1:8000/accounts/HospitalRegistration/
# http://127.0.0.1:8000/accounts/login/

# http://127.0.0.1:8000/accounts/UserRegistration/
# http://127.0.0.1:8000/accounts/userLogin/

MainProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('Accounts.urls')),
    path('administrator/',include("AdminiStrator.urls")),
    path('hospital/',include("Hospital.urls")),
    path('user/',include("user.urls")),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path,include
from user import views

app_name="user"
urlpatterns = [
    path('Homepage/',views.Homepage,name="user-homepage"),
    path('ViewProfile/',views.ViewProfile,name="user-profile"),
    path('AddComplaints/',views.AddComplaints,name="user-complaints")
   
]

Accounts/models.py
from django.db import models
from MasterEntry.models import Place,HospitalType

class Hospital(models.Model):
    hospital_name=models.CharField(max_length=20)
    hospital_contact=models.CharField(max_length=15)
    hospital_email=models.EmailField(default=True)
    hospital_address=models.TextField(blank=True)
    hospital_place=models.ForeignKey(Place,on_delete=models.SET_NULL,null=True)
    hospital_type=models.ForeignKey(HospitalType,on_delete=models.SET_NULL,null=True)
    hospital_proof=models.FileField(upload_to='HospitalProof/')
    hospital_image=models.ImageField(upload_to="HospitalImage/")
    hospital_username=models.CharField(max_length=15,default=True)
    hospital_password=models.CharField(max_length=15,default=True)
    hospital_status=models.IntegerField(default=0)
    hospital_doj=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.hospital_name

class Users(models.Model):
    user_name=models.CharField(max_length=10,default=True)
    user_contact=models.CharField(max_length=20,default=True)
    user_email=models.EmailField(default=True)
    #user_place=models.ForeignKey(Place,on_delete=models.SET_NULL,null=True)
    user_place=models.CharField(max_length=50,default=True)
    user_gender=models.CharField(max_length=20,default=True)
    user_username=models.CharField(max_length=20,default=True)
    user_password=models.CharField(max_length=20,default=True)
    user_status=models.IntegerField(default=0)

    def __str__(self):
        return self.user_name
    

Accounts/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from MasterEntry.models import District,Place,HospitalType
from .models import Hospital, Users
from MasterEntry.models import Place
from django.template import loader

# ------------------------------------------------------------------

def AjaxPalce(request):
    district=request.GET.get("districtid")
    placeList=Place.objects.filter(PlaceDistrict=district[0])
    return render(request,"Accounts/AjaxPlace.html",{"placeList":placeList})

# ----------------------------------------------------------------------





#------------------------------------------------------------------------


def Login(request):
    if request.method=='POST':
        hospitalDataCount=Hospital.objects.filter(hospital_username=request.POST.get("txtUsername"),hospital_password=request.POST.get("txtPassword")).count()
        usersDataCount=Users.objects.filter(user_username=request.POST.get("txtUsername"),user_password=request.POST.get("txtPassword")).count()
        print(hospitalDataCount)
        if hospitalDataCount>0:
     
            hospitalobj = get_object_or_404(Hospital, hospital_username=request.POST.get("txtUsername"),hospital_password=request.POST.get("txtPassword"))
            request.session["sessionHospitalId"]=hospitalobj.id
            request.session["sessionHospitalname"]=hospitalobj.hospital_name
            return redirect('/hospital/HomePage')
   
        elif usersDataCount>0:
            usersobj = get_object_or_404(Users, user_username=request.POST.get("txtUsername"),user_password=request.POST.get("txtPassword"))
            request.session["userid"]=usersobj.id
            request.session["username"]=usersobj.user_name
            return redirect('/user/Homepage')
        else: 
            return HttpResponse("Invalid Data")
    return render(request,"Accounts/Login.html",{})

#-------------------------------------------------------------------------------------------------

def  allDistricts():
    disitrictData=District.objects.all()
    return disitrictData
def allHospitalTypes():
    hospitalTypeData=HospitalType.objects.all()
    return hospitalTypeData

def RegisterHospital(request):
    DistrictRecords=allDistricts()
    HospitalTypeRecords=allHospitalTypes()

    if request.method=="POST" and request.FILES :
        hospitalObj=J=Hospital()
        hospitalObj.hospital_name=request.POST.get("txtHname")
        hospitalObj.hospital_contact=request.POST.get("txtHcontact")
        hospitalObj.hospital_email=request.POST.get("txtHemail")
        hospitalObj.hospital_address=request.POST.get("txtHospitalAddress")
        
        hospitaltypeObj=HospitalType.objects.get(id=request.POST.get("slctHtype"))
        hospitalObj.hospital_type=hospitaltypeObj

        hospitalPlaceObj=Place.objects.get(id=request.POST.get("slctPlace"))
        hospitalObj.hospital_place=hospitalPlaceObj
        
        hospitalObj.hospital_proof=request.FILES.get("fileHProof")
        hospitalObj.hospital_image=request.FILES.get("fileHImage")
        hospitalObj.hospital_username=request.POST.get("txtUsername")
        hospitalObj.hospital_password=request.POST.get("txtPassword")
        #hospitalObj.hospital_status=1
        hospitalObj.save()
        return redirect('/accounts/login')
    else:
        return render(request,"Accounts/NewHospital.html",{'DistrictRecords':DistrictRecords,'HospitalTypeRecords':HospitalTypeRecords})
        
        
        
     #----------------------------------------------------------------------------------------------------------------------------
        
def RegisterUser(request):
    if request.method=="POST" :
        usersObj=J=Users()
        usersObj.user_name=request.POST.get("txtUname")
        usersObj.user_contact=request.POST.get("txtUcontact")
        usersObj.user_email=request.POST.get("txtUemail")
        usersObj.user_place=request.POST.get("txtUPlace")
        usersObj.user_gender=request.POST.get("Ugender")
        usersObj.user_username=request.POST.get("txtUsername")
        usersObj.user_password=request.POST.get("txtPassword")
        usersObj.user_status=1
        usersObj.save()
        return redirect('/accounts/userLogin')
    else:
        return render(request,"Accounts/NewUser.html")   

def Registration(request) :
    return render(request,"Accounts/Registration.html")

Accounts/templates/Accounts/AjaxPlace.html
<option value="">---Select---</option>
{% for data in placeList %}
<option value="{{ data.id }}">{{ data.place_name }}</option>
{% endfor %}

Accounts/templates/Accounts/Login.html
<!DOCTYPE html>
<html lang="en" ><head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.0/css/bootstrapValidator.min.css">
    
    <style>
        #success_message{ display: none;}
    </style>
    <script>
        window.console = window.console || function(t) {};
    </script>
    <script>
        if (document.location.search.match(/type=embed/gi)) {
        window.parent.postMessage("resize", "*");
        }
    </script>
  </head>
  <body translate="no">
    <div class="container">

        <form action="" method="post" autocomplete="off" class="well form-horizontal bv-form" novalidate="novalidate" id="login_form">
            {% csrf_token %}
            <fieldset>
           
            <legend><center><h2><b>Login</b></h2></center></legend><br>
            
            <div class="form-group has-feedback">
                <label class="col-md-4 control-label">User name</label>  
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input name="txtUsername" id="txtUsername" placeholder="Username" class="form-control" type="text" data-bv-field="txt_Username"><i class="form-control-feedback" data-bv-icon-for="txt_Username" style="display: none;"></i>
                    </div>
                <small data-bv-validator="stringLength" data-bv-validator-for="txt_Username" class="help-block" style="display: none;">This value is not valid</small><small data-bv-validator="notEmpty" data-bv-validator-for="txt_Username" class="help-block" style="display: none;">Please enter Username</small></div>
            </div>
            
            <div class="form-group has-feedback">
                <label class="col-md-4 control-label">Password</label> 
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input name="txtPassword" id="txtPassword" placeholder="Password" class="form-control" type="password" data-bv-field="txt_Password"><i class="form-control-feedback" data-bv-icon-for="txt_Password" style="display: none;"></i>
                    </div>
                <small data-bv-validator="stringLength" data-bv-validator-for="txt_Password" class="help-block" style="display: none;">This value is not valid</small><small data-bv-validator="notEmpty" data-bv-validator-for="txt_Password" class="help-block" style="display: none;">Please enter the Password</small></div>
            </div>
            
            <div class="form-group">
                <label class="col-md-4 control-label"></label>
                <div class="col-md-4"><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <button type="submit" class="btn btn-warning">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Login <span class="glyphicon glyphicon-send"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</button>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'Accounts:HospitalSignup'%}" style="text-decoration: underline;">Register</a>
                </div>
            </div>
            
            </fieldset>
  <input type="hidden" value=""></form>
  </div>
      <script src="https://cpwebassets.codepen.io/assets/common/stopExecutionOnTimeout-157cd5b220a5c80d4ff8e0e70ac069bffd87a61252088146915e8726e5d9f147.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-validator/0.4.5/js/bootstrapvalidator.min.js"></script>
      <script id="rendered-js">
        $(document).ready(function () {
            $('#login_form').bootstrapValidator({
               
                feedbackIcons: {
                    valid: 'glyphicon glyphicon-ok',
                    invalid: 'glyphicon glyphicon-remove',
                    validating: 'glyphicon glyphicon-refresh' },
            
                fields: {
                    user_name: {
                    validators: {
                        stringLength: {
                        min: 8 },
            
                        notEmpty: {
                        message: 'Please enter the Username' } } },
            
                    txt_Password: {
                    validators: {
                        stringLength: {
                        min: 8 },
            
                        notEmpty: {
                        message: 'Please enter the Password' } } },
            
            } }).
            on('success.form.bv', function (e) {
            $('#success_message').slideDown({ opacity: "show" }, "slow"); 
            $('#login_form').data('bootstrapValidator').resetForm();
        
            // Prevent form submission
            e.preventDefault();
        
            // Get the form instance
            //var $form = $(e.target);
        
            // Get the BootstrapValidator instance
            //var bv = $form.data('bootstrapValidator');
        
            // Use Ajax to submit form data
            // $.post($form.attr('action'), $form.serialize(), function (result) {
            //     console.log(result);
            // }, 'json');
            });
        });
</script>
<script>
    $('form').attr('autocomplete','off');
</script>
</body></html>

Accounts/templates/Accounts/NewUser.html
<!DOCTYPE html>
<html lang="en" ><head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.0/css/bootstrapValidator.min.css">
  </head>
  <body translate="no">
    <div class="container">
  
      <!-- <form class="well form-horizontal bv-form" action=" " method="post" id="transac_form" novalidate="novalidate"> -->
        
        <form method="POST" autocomplete="off" class="well form-horizontal bv-form" novalidate="novalidate" action="{% url 'Accounts:UserSignup' %}" id="transac_form" data-cities-url="{% url 'Accounts:AjaxPlaces' %}">
            {% csrf_token %}
            <fieldset>
            
            <!-- Form Name -->
            <legend><center><h2><b>User Registration</b></h2></center></legend><br>
            
            <!-- Text input-->
            
            <div class="form-group has-feedback">
                <label class="col-md-4 control-label">Name</label>  
                <div class="col-md-4 inputGroupContainer">
                <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                <input name="txtUname" placeholder="Name" class="form-control" type="text" data-bv-field="txt_name"><i class="form-control-feedback" data-bv-icon-for="txt_name" style="display: none;"></i>
                </div>
                <small data-bv-validator="stringLength" data-bv-validator-for="txt_name" class="help-block" style="display: none;">This value is not valid</small><small data-bv-validator="notEmpty" data-bv-validator-for="txt_name" class="help-block" style="display: none;">Please enter your Name</small></div>
            </div>
            
            <!-- Text input-->
            
            <div class="form-group has-feedback">
                <label class="col-md-4 control-label">Contact</label> 
                <div class="col-md-4 inputGroupContainer">
                <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                <input name="txtUcontact" placeholder="Contact" class="form-control" type="text" data-bv-field="txt_contact"><i class="form-control-feedback" data-bv-icon-for="txt_contact" style="display: none;"></i>
                </div>
                <small data-bv-validator="stringLength" data-bv-validator-for="txt_contact" class="help-block" style="display: none;">This value is not valid</small><small data-bv-validator="notEmpty" data-bv-validator-for="txt_contact" class="help-block" style="display: none;">Please enter contact</small></div>
            </div>

            <!-- Text input-->
            <div class="form-group has-feedback">
                <label class="col-md-4 control-label">E-Mail</label>  
                <div class="col-md-4 inputGroupContainer">
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                    <input name="txtUemail" id="txtHemail" placeholder="E-Mail Address" class="form-control" type="text" data-bv-field="email"><i class="form-control-feedback" data-bv-icon-for="email" style="display: none;"></i>
                </div>
                <small data-bv-validator="notEmpty" data-bv-validator-for="email" class="help-block" style="display: none;">Please enter your Email Address</small><small data-bv-validator="emailAddress" data-bv-validator-for="email" class="help-block" style="display: none;">Please enter a valid Email Address</small></div>
            </div>
            
            <div class="form-group has-feedback">
                <label class="col-md-4 control-label">Place</label> 
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input name="txtUPlace" placeholder="Place" class="form-control" type="text" data-bv-field="txt_place"><i class="form-control-feedback" data-bv-icon-for="txt_place" style="display: none;"></i>
                    </div>
                <small data-bv-validator="stringLength" data-bv-validator-for="txt_place" class="help-block" style="display: none;">This value is not valid</small><small data-bv-validator="notEmpty" data-bv-validator-for="txt_place" class="help-block" style="display: none;">Please enter place</small></div>
            </div>

            <div class="form-group has-feedback">
                <label class="col-md-4 control-label">Gender</label> 
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <input type="radio" id="male" name="Ugender" value="Male" data-bv-field="txt_gender">&nbsp;&nbsp;Male&nbsp;&nbsp;
                        <input type="radio" id="female" name="Ugender" value="FeMale">&nbsp;&nbsp;Female
                    </div>
                </div>
            </div>

            <!-- Text input-->
            
            <div class="form-group has-feedback">
                <label class="col-md-4 control-label">User name</label>  
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input name="txtUsername" id="txtUsername" placeholder="Username" class="form-control" type="text" data-bv-field="txt_Username"><i class="form-control-feedback" data-bv-icon-for="txt_Username" style="display: none;"></i>
                    </div>
                <small data-bv-validator="stringLength" data-bv-validator-for="txt_Username" class="help-block" style="display: none;">This value is not valid</small><small data-bv-validator="notEmpty" data-bv-validator-for="txt_Username" class="help-block" style="display: none;">Please enter Username</small></div>
            </div>
            
            <!-- Text input-->
            
            <div class="form-group has-feedback">
                <label class="col-md-4 control-label">Password</label> 
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input name="txtPassword" id="txtPassword" placeholder="Password" class="form-control" type="password" data-bv-field="txt_Password"><i class="form-control-feedback" data-bv-icon-for="txt_Password" style="display: none;"></i>
                    </div>
                <small data-bv-validator="stringLength" data-bv-validator-for="txt_Password" class="help-block" style="display: none;">This value is not valid</small><small data-bv-validator="notEmpty" data-bv-validator-for="txt_Password" class="help-block" style="display: none;">Please enter the Password</small></div>
            </div>
        
            <!-- Button -->
            <div class="form-group">
                <label class="col-md-4 control-label"></label>
                <div class="col-md-4"><br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button type="submit" class="btn btn-warning">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Register Now <span class="glyphicon glyphicon-send"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</button>
                </div>
            </div>
            
            </fieldset>
  <input type="hidden" value=""></form>
  </div>
      <!-- /.container -->
      <script src="https://cpwebassets.codepen.io/assets/common/stopExecutionOnTimeout-157cd5b220a5c80d4ff8e0e70ac069bffd87a61252088146915e8726e5d9f147.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-validator/0.4.5/js/bootstrapvalidator.min.js"></script>
      <script id="rendered-js">
        $(document).ready(function () {
            $('#transac_form').bootstrapValidator({
               
            // To use feedback icons, ensure that you use Bootstrap v3.1.0 or later
            feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh' },
        
            fields: {
                txt_name: {
                validators: {
                    stringLength: {
                    min: 2 },
        
                    notEmpty: {
                    message: 'Please enter the Name' } } },

                txt_contact: {
                validators: {
                    stringLength: {
                    min: 2 },
        
                    notEmpty: {
                    message: 'Please enter the contact' } } },
        
                user_name: {
                validators: {
                    stringLength: {
                    min: 8 },
        
                    notEmpty: {
                    message: 'Please enter the Username' } } },
        
                txt_Password: {
                validators: {
                    stringLength: {
                    min: 8 },
        
                    notEmpty: {
                    message: 'Please enter the Password' } } },
        
                email: {
                validators: {
                    notEmpty: {
                    message: 'Please enter the Email Address' },
        
                    emailAddress: {
                    message: 'Please enter a valid Email Address' } } },
        
                } }).
                alert("hi");
            on('success.form.bv', function (e) {
                alert("hii")
            $('#success_message').slideDown({ opacity: "show" }, "slow"); // Do something ...
            $('#transac_form').data('bootstrapValidator').resetForm();
        
            // Prevent form submission
            e.preventDefault();
        
            // Get the form instance
            var $form = $(e.target);
        
            // Get the BootstrapValidator instance
            var bv = $form.data('bootstrapValidator');
        
            // Use Ajax to submit form data
            $.post($form.attr('action'), $form.serialize(), function (result) {
                console.log(result);
            }, 'json');
            });
        });
        //# sourceURL=pen.js
        function LoadPlace(did){
            var url = $("#transac_form").attr("data-cities-url");  
            var districtSelected = did 
            //alert(districtSelected)
            $.ajax({                      
            url: url,                   
            data: {
                'districtid': districtSelected       
            },
            success: function (data) { 
                $("#slctPlace").html(data);  
            }
            });
        }
</script>
<script>
    $('form').attr('autocomplete','off');
</script>
</body></html>

Accounts/templates/Accounts/Registration.html
<!DOCTYPE html>
<html lang="en" ><head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script>
        window.console = window.console || function(t) {};
    </script>
  </head>
  <body translate="no">
    <div class="container">
        <form action="" method="post" class="well form-horizontal bv-form" novalidate="novalidate" id="login_form">
            <legend><center><h2>Registration</b> </h2></center></legend><br>
            <br>
            <a href="{% url 'Accounts:UserSignup' %}" style="text-decoration: underline;">User Registration</a>
            <a href="{% url 'Accounts:HospitalSignup' %}" style="text-decoration: underline;" >Hospital Registration</a>
        </form>
    </div>
  </body>
  </html>