AdminiStrator/urls.py
from django.urls import path,include
from AdminiStrator import views

app_name="AdminiStrator"
urlpatterns = [
    path('HomePage/',views.Homepage,name="admin-homepage"),
    path("HospitalVerification/",views.PendingHospitalVerification,name="pending-hospital-verification"),
    path("AcceptingHospital/<int:id>",views.AcceptHospital,name="accept-hospitals"),
    path("RejectingingHospital/<int:id>",views.RejectHospital,name="reject-hospitals"),
    path("ViewAcceptedHospitals/",views.AcceptedHospitalList,name="accepted-hospital-list"),
    path("ViewRejectedHospitals/",views.RejectedHospitalList,name="rejected-hopital-list"),
    path("ViewUsersComplaints/",views.ViewUsersComplaints,name="view-user-complaints"),
    path("ViewHospitalComplaints/",views.ViewHospitalComplaints,name="view-hospital-complaints")
]

MainProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('Accounts.urls')),
    path('administrator/',include("AdminiStrator.urls")),
    path('hospital/',include("Hospital.urls")),
    path('user/',include("user.urls")),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path,include
from user import views

app_name="user"
urlpatterns = [
    path('Homepage/',views.Homepage,name="user-homepage"),
    path('ViewProfile/',views.ViewProfile,name="user-profile"),
    path('AddComplaints/',views.AddComplaints,name="user-complaints")
   
]

AdminiStrator/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from Accounts.models import Hospital
from Hospital.models import Complaints
from user.models import UserComplaints

def Homepage(request):
    return render(request,"Administrator/HomePage.html",{})

def PendingHospitalVerification(request):
    recordSet=Hospital.objects.filter(hospital_status=0)
    return render(request,"AdminiStrator/HospitalVerifications.html",{"HospitalData":recordSet})

def AcceptHospital(request,id):
    hospitalData=Hospital.objects.get(id=id)
    hospitalData.hospital_status=1
    hospitalData.save()
    return redirect("/administrator/HospitalVerification")

def RejectHospital(request,id):
    hospitalData=Hospital.objects.get(id=id)
    hospitalData.hospital_status=2
    hospitalData.save()
    return redirect("/administrator/HospitalVerification")

def AcceptedHospitalList(request):
    recordSet=Hospital.objects.filter(hospital_status=1)
    return render(request,"AdminiStrator/AcceptedHospitals.html",{"HospitalData":recordSet})


def RejectedHospitalList(request):
    recordSet=Hospital.objects.filter(hospital_status=2)
    return render(request,"AdminiStrator/RejectedHospitals.html",{"HospitalData":recordSet})

def ManageStaffs(request):
    pass

def ManageMobileServices(request):
    pass

def ManageServicesPackages(request):
    pass

def ViewHospitalComplaints(request):
    if request.method=="POST":
        print(request.POST.get("hiddenHospitalId"))
        return redirect('/administrator/HomePage')
    else :
        recordSet=Complaints.objects.filter(hcomplaint_isfix="No")
        return render(request,"AdminiStrator/ViewHospitalComplants.html",{"hospitalComplaints":recordSet})

def ViewUsersComplaints(request):
    recordSet=UserComplaints.objects.filter(ucomplaint_isfix="No")
    return render(request,"AdminiStrator/ViewUsersComplaints.html",{"userComplaints":recordSet})

def ReplyHospitalComplaints(request):
    #recordSet=Complaints.objects.filter(hcomplaint_isfix="No")
    return redirect('/administrator/HomePage')


    

AdminiStrator/templates/AdminiStrator/AcceptedHospitals.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table align="center" border="1" cellpadding="10" style="border-collapse: collapse;">
        <tr>
            <th>Name</th>
            <th>Contact</th>
            <th>Email</th>
            <th>Address</th>
            <th>Type</th>
            <th colspan="2">Actions</th>
        </tr>

        {% for Data in HospitalData %}
        <tr>
            <td>{{ Data.hospital_name }}</td>
            <td>{{ Data.hospital_contact }}</td>
            <td>{{ Data.hospital_email }}</td>
            <td>{{ Data.hospital_address }}</td>
            <td>{{ Data.hospital_type }}</td>
            <td><img src="{{Data.hospital_image.url}}" width="120" height="120"></td>
            
           
            
        </tr>
        {% endfor %}
    </table>



</body>
</html>

AdminiStrator/templates/AdminiStrator/HomePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'AdminiStrator:admin-homepage' %}">Homepage</a>
    <a href="{% url 'AdminiStrator:pending-hospital-verification' %}">Verify Hospitals</a>
    <a href="{% url 'AdminiStrator:accepted-hospital-list' %}">Accepted Hospitals</a>
    <a href="{% url 'AdminiStrator:rejected-hopital-list' %}">Rejected Hospitals</a>
</body>
</html>

AdminiStrator/templates/AdminiStrator/HospitalVerifications.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table align="center" border="1" cellpadding="10" style="border-collapse: collapse;">
        <tr>
            <th>Name</th>
            <th>Contact</th>
            <th>Email</th>
            <th>Address</th>
            <th>Type</th>
            <th colspan="2">Actions</th>
        </tr>

        {% for Data in HospitalData %}
        <tr>
            <td>{{ Data.hospital_name }}</td>
            <td>{{ Data.hospital_contact }}</td>
            <td>{{ Data.hospital_email }}</td>
            <td>{{ Data.hospital_address }}</td>
            <td>{{ Data.hospital_type }}</td>
            <td><img src="{{Data.hospital_image.url}}" width="120" height="120"></td>
            
            <td colspan="2">
                <a href="{% url 'AdminiStrator:accept-hospitals' Data.id %}">Accept</a>
                <a href="{% url 'AdminiStrator:reject-hospitals' Data.id %}">Reject</a>
            </td>
            
        </tr>
        {% endfor %}
    </table>



</body>
</html>

AdminiStrator/templates/AdminiStrator/RejectedHospitals.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table align="center" border="1" cellpadding="10" style="border-collapse: collapse;">
        <tr>
            <th>Name</th>
            <th>Contact</th>
            <th>Email</th>
            <th>Address</th>
            <th>Type</th>
            <th colspan="2">Actions</th>
        </tr>

        {% for Data in HospitalData %}
        <tr>
            <td>{{ Data.hospital_name }}</td>
            <td>{{ Data.hospital_contact }}</td>
            <td>{{ Data.hospital_email }}</td>
            <td>{{ Data.hospital_address }}</td>
            <td>{{ Data.hospital_type }}</td>
            <td><img src="{{Data.hospital_image.url}}" width="120" height="120"></td>
            
           
            
        </tr>
        {% endfor %}
    </table>



</body>
</html>

AdminiStrator/templates/AdminiStrator/ViewHospitalComplants.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table align="center" border="1" cellpadding="10" style="border-collapse: collapse;">
        <tr>
            <th>Hospital Name</th>
            <th>Complaint Type</th>
            <th>Content</th>
            <th>Date</th>
            <th>Reply</th>
        </tr>
        {% for Data in hospitalComplaints %}
        <tr>
            <td>{{ Data.hcomplaint_hospital }}</td>
            <td>{{ Data.hcomplaint_type }}</td>
            <td>{{ Data.hcomplaint_content }}</td>
            <td>{{ Data.hcomplaint_date }}</td>
            <td colspan="2">
                <input type="text" name="hReply"/>
            </td>
        </tr>
        {% endfor %}
    </table>
    <br>
    <div style="text-align: center;">
        <button>Submit</button>
    </div>
</body>
</html>

AdminiStrator/templates/AdminiStrator/ViewUsersComplaints.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table align="center" border="1" cellpadding="10" style="border-collapse: collapse;">
        <tr>
            <th>User Name</th>
            <th>Complaint Type</th>
            <th>Content</th>
            <th>Date</th>
            <th>Reply</th>
        </tr>
        {% for Data in userComplaints %}
        <tr>
            <td>{{ Data.ucomplaint_user }}</td>
            <td>{{ Data.ucomplaint_type }}</td>
            <td>{{ Data.ucomplaint_content }}</td>
            <td>{{ Data.ucomplaint_date }}</td>
            <td colspan="2">
                <input type="text" name="uReply" />
            </td>
        </tr>
        {% endfor %}
    </table>
    <br>
    <div style="text-align: center;">
        <button>Submit</button>
    </div>
</body>
</html>