MainProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('Accounts.urls')),
    path('administrator/',include("AdminiStrator.urls")),
    path('hospital/',include("Hospital.urls")),
    path('user/',include("user.urls")),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path,include
from user import views

app_name="user"
urlpatterns = [
    path('Homepage/',views.Homepage,name="user-homepage"),
    path('ViewProfile/',views.ViewProfile,name="user-profile"),
    path('AddComplaints/',views.AddComplaints,name="user-complaints")
   
]

user/models.py
from django.db import models
from MasterEntry.models import ComplaintType
from Accounts.models import Users
from Hospital.models import Mobilehospital

class UserComplaints(models.Model):
    ucomplaint_user=models.ForeignKey(Users,on_delete=models.SET_NULL,null=True)
    ucomplaint_type=models.ForeignKey(ComplaintType,on_delete=models.SET_NULL,null=True)
    ucomplaint_mobile_hospital=models.ForeignKey(Mobilehospital,on_delete=models.SET_NULL,null=True)
    ucomplaint_content=models.TextField(null=False)
    ucomplaint_date=models.DateField(auto_now_add=True)
    ucomplaint_time=models.TimeField(auto_now_add=True)
    ucomplaint_isfix=models.CharField(max_length=5,default="No")

user/views.py
from django.shortcuts import redirect, render
from Accounts.models import Users,Hospital
from MasterEntry.models import Place,ComplaintType
from .models import UserComplaints
from Hospital.models import Mobilehospital

def Homepage(request):
    if 'userid' not in request.session:
        return redirect('/accounts/userLogin')
    else :
        return render(request,"user/HomePage.html",{})

def ViewProfile(request):
    if 'userid' not in request.session:
        return redirect('/accounts/userLogin')
    else :
        UserData=Users.objects.get(id=request.session["userid"])
        context={
            "UserName":UserData.user_name,
            "UserContact":UserData.user_contact,
            "UserEmail":UserData.user_email,
            "UserGender":UserData.user_gender,
            "UserUserName":UserData.user_username,
            "UserPlace":UserData.user_place
        }
        return render(request,"user/ViewProfile.html",context)

def AddComplaints(request):
    userObj=Users.objects.get(id=request.session["userid"])
    ComplainttypeRecords = ComplaintType.objects.all()
    mobileHospitalData = Mobilehospital.objects.all()
    print(request.POST.get("slctMobileHospital"))
    if request.method=="POST":
        UserComplaints.objects.create(
            ucomplaint_user=userObj,
            ucomplaint_mobile_hospital=Mobilehospital.objects.get(id=request.POST.get("slctMobileHospital")),
            ucomplaint_type=ComplaintType.objects.get(id=request.POST.get("slctComplaintType")),
            ucomplaint_content=request.POST.get("txtcontent")
        )
        return render(request,"user/ComplaintBox.html",{"ComplaintType":ComplainttypeRecords,"mobileHospitalData":mobileHospitalData})
    else:
        return render(request,"user/ComplaintBox.html",{"ComplaintType":ComplainttypeRecords,"mobileHospitalData":mobileHospitalData})

    

user/templates/user/ComplaintBox.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
    

    <table align="center" cellpadding="10" border="1" style="border-collapse: collapse;">
       
        <tr>
            <td>Mobile Hospital</td>
            <td>
                <select name="slctMobileHospital" id="">
                    <option value="">---Select---</option>
                    {% for data  in  mobileHospitalData %}
                      <option value="{{ data.id }}">{{ data.service_no }}</option>
                    {% endfor %}
                </select>
            </td>
        </tr>
        <tr>
            <td>Complaint Type</td>
            <td>
                <select name="slctComplaintType" id="">
                    <option value="">---Select---</option>
                    {% for data  in  ComplaintType %}
                      <option value="{{ data.id }}">{{ data.complainttype_name }}</option>
                    {% endfor %}
                </select>
            </td>
        </tr>    
        <tr>
            <td>Content</td>
            <td><textarea name="txtcontent" id="" cols="30" rows="10"></textarea></td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" name="btnSave" value="Add Service">
            </td>
        </tr>
    </table>
    
</body>
</html>

user/templates/user/Homepage.html
<!DOCTYPE html>
<html lang="en" ><head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  </head>
  <body translate="no">
    <div class="container">
        <form action="" method="post" class="well form-horizontal bv-form" novalidate="novalidate" id="login_form">
            <legend><center><h2>Welcome <b>{{ request.session.sessionUsername }}</b> </h2></center></legend><br>
            <br>
            <b>User Portal</b>
            <a href="{% url 'user:user-homepage'%}">Homepage</a>&nbsp; |
            <a href="{% url 'user:user-profile'%}">View Profile</a>&nbsp; |
            <a href="{% url 'user:user-complaints'%}">Add Complaints</a>
        </form>
    </div>
  </body>
  </html>

user/templates/user/ViewProfile.html
<!DOCTYPE html>
<html lang="en" ><head>
    <meta charset="UTF-8">
    <link rel="apple-touch-icon" type="image/png" href="https://cpwebassets.codepen.io/assets/favicon/apple-touch-icon-5ae1a0698dcc2402e9712f7d01ed509a57814f994c660df9f7a952f3060705ee.png">
    <link rel="shortcut icon" type="image/x-icon" href="https://cpwebassets.codepen.io/assets/favicon/favicon-aec34940fbc1a6e787974dcd360f2c6b63348d4b1f4e06c77743096d55480f33.ico">
    <link rel="mask-icon" type="" href="https://cpwebassets.codepen.io/assets/favicon/logo-pin-8f3771b1072e3c38bd662872f6b673a722f4b3ca2421637d5596661b4e2132cc.svg" color="#111">
    <title>CodePen - Bootstrap 3 Registration Form with Validation</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.0/css/bootstrapValidator.min.css">
    
  </head>
  <body translate="no">
    <div class="container">
  
        <form action="" method="post" class="well form-horizontal bv-form" novalidate="novalidate" id="login_form">
            {% csrf_token %}
            <fieldset>
            
            <!-- Form Name -->
            <legend><center><h2><b>Profile</b></h2></center></legend><br>
            
            <div class="form-group ">
                <label class="col-md-6 control-label">Name</label>  
                <div class="col-md-6 inputGroupContainer" style="padding-top: 8px;">
                    <div class="input-group">
                        {{ UserName  }}
                    </div>
                </div>
            </div>
            <div class="form-group ">
                <label class="col-md-6 control-label">Gender</label>  
                <div class="col-md-6 inputGroupContainer" style="padding-top: 8px;">
                    <div class="input-group">
                        {{ UserGender  }}
                    </div>
                </div>
            </div>   
            <div class="form-group ">
                <label class="col-md-6 control-label">Contact</label>  
                <div class="col-md-6 inputGroupContainer" style="padding-top: 8px;">
                    <div class="input-group">
                        {{ UserContact  }}
                    </div>
                </div>
            </div>
            <div class="form-group ">
                <label class="col-md-6 control-label">Email</label>  
                <div class="col-md-6 inputGroupContainer" style="padding-top: 8px;">
                    <div class="input-group">
                        {{ UserEmail   }}
                    </div>
                </div>
            </div>
            <div class="form-group ">
                <label class="col-md-6 control-label">Place</label>  
                <div class="col-md-6 inputGroupContainer" style="padding-top: 8px;">
                    <div class="input-group">
                        {{ UserPlace  }}
                    </div>
                </div>
            </div>
            <div class="form-group ">
                <label class="col-md-6 control-label">User Name</label>  
                <div class="col-md-6 inputGroupContainer" style="padding-top: 8px;">
                    <div class="input-group">
                        {{ UserUserName  }}
                    </div>
                </div>
            </div>            
            </fieldset>
  <input type="hidden" value=""></form>
  </div>
      <!-- /.container -->
      <script src="https://cpwebassets.codepen.io/assets/common/stopExecutionOnTimeout-157cd5b220a5c80d4ff8e0e70ac069bffd87a61252088146915e8726e5d9f147.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-validator/0.4.5/js/bootstrapvalidator.min.js"></script>
  </body></html>