Accounts/urls.py
from django.urls import path,include
from Accounts import views

app_name="Accounts"
urlpatterns = [
    path("login/",views.Login,name="login"),
    path("HospitalRegistration/",views.RegisterHospital,name="HospitalSignup"),
    path("Ajax_load_place/",views.AjaxPalce,name="AjaxPlaces"),
    path("UserRegistration/",views.RegisterUser,name="UserSignup"),
    path("Registration/",views.Registration,name="Registration")
]


# Accounts URLS

# http://127.0.0.1:8000/accounts/Registration/

# http://127.0.0.1:8000/accounts/HospitalRegistration/
# http://127.0.0.1:8000/accounts/login/

# http://127.0.0.1:8000/accounts/UserRegistration/
# http://127.0.0.1:8000/accounts/userLogin/

Hospital/urls.py
from django.urls import path,include
from Hospital import views

app_name="Hospital"
urlpatterns = [
    path('HomePage/',views.Homepage,name="hospital-homepage"),
    path('ViewProfile/',views.ViewProfile,name="hospital-profile"),
    path('dailyservices/',views.DailyService,name="daily-services"),
    path('servicepackages/',views.ServicePackage,name="services-packages"),
    path('servicestaffs/',views.ServiceStaff,name="services-staffs"),
    path('ViewDailyService/',views.ViewDailyService,name="view-daily-services"),
    path('ViewPackages/',views.ViewPackages,name="view-packages"),
    path('ViewStaffs/',views.ViewStaffs,name="view-staffs"),
    path('UserComplaints/',views.UserComplaints,name="user-complaints"),
    path('AddComplaints/',views.AddComplaints,name="user-add-complaint"),
]

MainProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('Accounts.urls')),
    path('administrator/',include("AdminiStrator.urls")),
    path('hospital/',include("Hospital.urls")),
    path('user/',include("user.urls")),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path,include
from user import views

app_name="user"
urlpatterns = [
    path('Homepage/',views.Homepage,name="user-homepage"),
    path('ViewProfile/',views.ViewProfile,name="user-profile"),
    path('AddComplaints/',views.AddComplaints,name="user-complaints")
   
]

Hospital/models.py
from django.db import models
from Accounts.models import Hospital
from MasterEntry.models import ServiceType,ServiceDesignation,ComplaintType

class dailyservice(models.Model):
    service_code=models.CharField(max_length=10,null=False,unique=True)
    service_type=models.CharField(max_length=5,null=False)
    service_rate=models.CharField(max_length=5,null=False)
    service_description=models.TextField()
    service_facilities=models.TextField()
    service_kmrate=models.CharField(max_length=5,null=False)
    service_hospital=models.ForeignKey(Hospital,on_delete=models.SET_NULL,null=True)

class servicespackage(models.Model):
    sp_code=models.CharField(max_length=10,null=False,unique=True)
    sp_rate=models.CharField(max_length=10,null=False)
    sp_duration=models.CharField(max_length=10,null=False)
    sp_facilitites=models.TextField()
    sp_type=models.ForeignKey(ServiceType,on_delete=models.SET_NULL,null=True)
    sp_hospital=models.ForeignKey(Hospital,on_delete=models.SET_NULL,null=True)

class servicestaff(models.Model):
    staff_name=models.CharField(max_length=10,null=False,default=False)
    staff_designation=models.ForeignKey(ServiceDesignation,on_delete=models.SET_NULL,null=True)
    staff_gender=models.CharField(max_length=10,null=False)
    staff_contact=models.CharField(max_length=11,null=False)
    staff_email=models.EmailField(max_length=11,null=False,unique=True)
    staff_photo=models.ImageField(upload_to="StaffPhoto/")
    staff_username=models.CharField(max_length=11,null=False,unique=True)
    staff_password=models.CharField(max_length=11,null=False,unique=True)
    staff_isactive=models.CharField(max_length=11,null=False,default="Yes")
    staff_unitcode=models.CharField(max_length=11,null=False,unique=True)
    staff_hospital=models.ForeignKey(Hospital,on_delete=models.SET_NULL,null=True)

class Complaints(models.Model):
    hcomplaint_hospital=models.ForeignKey(Hospital,on_delete=models.SET_NULL,null=True)
    hcomplaint_type=models.ForeignKey(ComplaintType,on_delete=models.SET_NULL,null=True)
    hcomplaint_content=models.TextField()
    hcomplaint_date=models.DateField(auto_now_add=True)
    hcomplaint_time=models.TimeField(auto_now_add=True)
    hcomplaint_isfix=models.CharField(max_length=5,default="No")

class Mobilehospital(models.Model):
    service_no=models.CharField(max_length=10,null=False,unique=True)
    service_type=models.ForeignKey(ServiceType,on_delete=models.SET_NULL,null=True)
    service_rate=models.IntegerField(null=False,unique=True)
    service_image=models.ImageField(upload_to="MobileHospitalPhoto/")
    service_description=models.TextField(null=False)
    service_basicrate=models.IntegerField(null=False,unique=True)
    service_km_rate=models.IntegerField(null=False,unique=True)
    service_status=models.CharField(max_length=10,null=False,unique=True)

Hospital/views.py
from django.db.models.fields import DateField, TimeField
from django.shortcuts import render
from django.shortcuts import redirect
from Accounts.models import Hospital
from MasterEntry.models import Place,ServiceDesignation,ServiceType,ComplaintType
from .models import dailyservice, servicespackage, servicestaff,Complaints


def Homepage(request):
    if 'sessionHospitalId' not in request.session:
        return redirect('/accounts/login')
    else :
        return render(request,"Hospital/HomePage.html",{})

def ViewProfile(request):
    if 'sessionHospitalId' not in request.session:
        return redirect('/accounts/login')
    else :
        HospitalData=Hospital.objects.get(id=request.session["sessionHospitalId"])
        placeData=Place.objects.get(id=HospitalData.hospital_place_id)
    
        context={
            "HospitalName":HospitalData.hospital_name,
            "HospitalContact":HospitalData.hospital_contact,
            "HospitalEmail":HospitalData.hospital_email,
            "HospitalAddress":HospitalData.hospital_address,
            "HospitalDistrict":placeData.PlaceDistrict,
            "HospitalPlace":HospitalData.hospital_place,
            "HopitalImage":HospitalData.hospital_image,
        }
        return render(request,"Hospital/ViewProfile.html",context)

def DailyService(request):
   
    hospitalObj=Hospital.objects.get(id=request.session["sessionHospitalId"])
  
    allServices=dailyservice.objects.filter(service_hospital=hospitalObj)
    if request.method=="POST":
        
        dailyservice.objects.create(
                service_code=request.POST.get("txtServiceCode"),
                service_type=request.POST.get("slctServiceType"),
                service_rate=request.POST.get("txtServiceRate"),
                service_description=request.POST.get("txtDescription"),
                service_facilities=request.POST.get("txtFacilitites"),
                service_kmrate=request.POST.get("txtKmRate"),
                service_hospital=hospitalObj
            )
        return render(request,"Hospital/ManageDailyServices.html",{"allServices":allServices})
    else:
        return render(request,"Hospital/ManageDailyServices.html",{"allServices":allServices})
    

def ServicePackage(request):
    hospitalObj=Hospital.objects.get(id=request.session["sessionHospitalId"])
    serviceTypeRecords=ServiceType.objects.all()
    if request.method=="POST":
        servicespackage.objects.create(
            sp_code=request.POST.get("txtPackageCode"),
            sp_rate=request.POST.get("txtPackageRate"),
            sp_duration=request.POST.get("txtDuration"),
            sp_facilitites=request.POST.get("txtFacilitites"),
            sp_type=ServiceType.objects.get(id=request.POST.get("slctServiceType")),
            sp_hospital= hospitalObj
        )
        return render(request,"Hospital/ManagePackages.html",{"ServiceTypes":serviceTypeRecords})
    else:
        return render(request,"Hospital/ManagePackages.html",{"ServiceTypes":serviceTypeRecords})


def ServiceStaff(request):
    hospitalObj=Hospital.objects.get(id=request.session["sessionHospitalId"])
    serviceDesignationRecords=ServiceDesignation.objects.all()
    if request.method=="POST" and request.FILES:
        servicestaff.objects.create(
            
            staff_name=request.POST.get("txtStaffName"),
            staff_designation=ServiceDesignation.objects.get(id=request.POST.get("slctDesignation")),
            staff_gender=request.POST.get("rdbGender"),
            staff_contact=request.POST.get("txtContact"),
            staff_email=request.POST.get("txtEmail"),
            staff_photo=request.FILES.get("fileStaffPhoto"),
            staff_username=request.POST.get("txtUsername"),
            staff_password=request.POST.get("txtPassword"),
            staff_unitcode=request.POST.get("txtStaffCode"),
            staff_hospital=hospitalObj
        )
        return render(request,"Hospital/ManageStaffs.html",{"ServiceDesignations":serviceDesignationRecords})
    else:
        return render(request,"Hospital/ManageStaffs.html",{"ServiceDesignations":serviceDesignationRecords})

def ViewDailyService(request):
    if 'sessionHospitalId' not in request.session:
        return redirect('/accounts/login')
    else :
        ServiceData=dailyservice.objects.get(service_hospital=request.session["sessionHospitalId"])
    
        context={
            "ServiceCode":ServiceData.service_code,
            "ServiceType":ServiceData.service_type,
            "ServiceRate":ServiceData.service_rate,
            "Description":ServiceData.service_description,
            "Facilities":ServiceData.service_facilities,
            "KMRate":ServiceData.service_kmrate,
           
        }
        return render(request,"Hospital/ViewDailyService.html",context)

def ViewPackages(request):
    if 'sessionHospitalId' not in request.session:
        return redirect('/accounts/login')
    else :
        PackageData=servicespackage.objects.get(sp_hospital=request.session["sessionHospitalId"])
        
        context={
            "PackageCode":PackageData.sp_code,
            "PackageType":PackageData.sp_type,
            "PackageRate":PackageData.sp_rate,
            "Duration":PackageData.sp_duration,
            "Facilities":PackageData.sp_facilitites,
            "KMRate":PackageData.sp_rate,
        }
        return render(request,"Hospital/ViewPackages.html",context)

def ViewStaffs(request):
    if 'sessionHospitalId' not in request.session:
        return redirect('/accounts/login')
    else :
        StaffData=servicestaff.objects.get(staff_hospital=request.session["sessionHospitalId"])
    
        context={
            "StaffCode":StaffData.staff_unitcode,
            "Name":StaffData.staff_name,
            "Contact":StaffData.staff_contact,
            "Gender":StaffData.staff_gender,
            "Email":StaffData.staff_email,
            "Designation":StaffData.staff_designation,
            "StaffImage":StaffData.staff_photo,
        }
        return render(request,"Hospital/ViewStaffs.html",context)

def AddComplaints(request):
    hospitalObj=Hospital.objects.get(id=request.session["sessionHospitalId"])
    ComplaintTypeRecords = ComplaintType.objects.all()
    if request.method=="POST":
        Complaints.objects.create(
            hcomplaint_hospital=hospitalObj,
            hcomplaint_type=ComplaintType.objects.get(id=request.POST.get("slctComplaintType")),
            hcomplaint_content=request.POST.get("txtcontent")
        )
        return render(request,"Hospital/ComplaintBox.html",{"Complainttype":ComplaintTypeRecords})
    else:
        return render(request,"Hospital/complaintBox.html",{"Complainttype":ComplaintTypeRecords})

def UserComplaints(request):
    recordSet=UserComplaints.objects.filter(ucomplaint_mobile_hospital_id=request.session["sessionHospitalId"])
    return render(request,"Hospital/ViewUsersComplaints.html",{"usersComplaints":recordSet})

Hospital/templates/Hospital/ChangePassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

Hospital/templates/Hospital/ComplaintBox.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

Hospital/templates/Hospital/EditProfile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

Hospital/templates/Hospital/HomePage.html
<!DOCTYPE html>
<html lang="en" ><head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script>
        window.console = window.console || function(t) {};
    </script>
  </head>
  <body translate="no">
    <div class="container">
        <form action="" method="post" class="well form-horizontal bv-form" novalidate="novalidate" id="login_form">
            <legend><center><h2>Welcome <b>{{ request.session.sessionHospitalname }}</b> </h2></center></legend><br>
            <br>
            <b>Hospital Portal</b>
            <a href="{% url 'Hospital:hospital-homepage'%}">Homepage</a>&nbsp; |
            <a href="{% url 'Hospital:hospital-profile'%}">View Profile</a>&nbsp; |
            <a href="{% url 'Hospital:daily-services'%}">Manage Daily Services</a>&nbsp; |
            <a href="{% url 'Hospital:services-packages'%}">Service Packages</a>&nbsp; |
            <a href="{% url 'Hospital:services-staffs'%}">Service Staffs</a>&nbsp; |
            <a href="{% url 'Hospital:view-daily-services'%}">View Daily Services</a>&nbsp; |
            <a href="{% url 'Hospital:view-packages'%}">View Packages</a>&nbsp; |
            <a href="{% url 'Hospital:view-staffs'%}">View Staffs</a>&nbsp; |
            <a href="{% url 'Hospital:user-add-complaint'%}">Add Complaint</a>&nbsp; |
            <a href="{% url 'Hospital:user-complaints'%}">View User Complaints</a>
        </form>
    </div>
  </body>
  </html>

Hospital/templates/Hospital/ManageDailyServices.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<form action="" method="post">
        {% csrf_token %}
    

    <table align="center" cellpadding="10" border="1" style="border-collapse: collapse;">
        <tr>
            <td>Code</td>
            <td><input type="text" name="txtServiceCode"></td>
        </tr>
        <tr>
            <td>Type</td>
            <td>
                <select name="slctServiceType" id="">
                    <option value="">---Select---</option>
                    <option value="Kids">For Kids</option>
                    <option value="Adults">For Adults</option>
                    <option value="Ladies">For Ladies</option>
                </select>
            </td>
        </tr>
        <tr>
            <td>Rate</td>
            <td><input type="text" name="txtServiceRate"></td>
        </tr>
        <tr>
            <td>Description</td>
            <td><textarea name="txtDescription" id="" cols="30" rows="10"></textarea></td>
        </tr>
        <tr>
            <td>Facilities</td>
            <td><textarea name="txtFacilitites" id="" cols="30" rows="10"></textarea></td>
        </tr>
        <tr>
            <td>KM/Rate</td>
            <td><input type="text" name="txtKmRate"></td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" name="btnSave" value="Add Service">
            </td>
        </tr>
    </table>
</form>
</body>
</html>

Hospital/templates/Hospital/ManagePackages.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<form action="" method="post">
        {% csrf_token %}
    

    <table align="center" cellpadding="10" border="1" style="border-collapse: collapse;">
        <tr>
            <td>Code</td>
            <td><input type="text" name="txtPackageCode"></td>
        </tr>
        <tr>
            <td>Type</td>
            <td>
                <select name="slctServiceType" id="">
                    <option value="">---Select---</option>
                    {% for data  in  ServiceTypes %}
                      <option value="{{ data.id }}">{{ data.servicetype_name }}</option>
                    {% endfor %}
                </select>
            </td>
        </tr>
        <tr>
            <td>Rate</td>
            <td><input type="text" name="txtPackageRate"></td>
      
        <tr>
            <tr>
                <td>Duration</td>
                <td><input type="text" name="txtDuration">(In Days)</td>
          
            <tr>
            <td>Facilities</td>
            <td><textarea name="txtFacilitites" id="" cols="30" rows="10"></textarea></td>
        </tr>
        <tr>
            <td>KM/Rate</td>
            <td><input type="text" name="txtKmRate"></td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" name="btnSave" value="Add Package">
            </td>
        </tr>
    </table>
</form>
</body>
</html>

Hospital/templates/Hospital/ManageStaffs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data" action="" id="transac_form" data-cities-url="{% url 'Accounts:AjaxPlaces' %}">
    {% csrf_token %}
    <table align="center" style="border-collapse: collapse;" border="1" cellpadding="10">
        <tr>
            <td>Staff Code</td>
            <td><input type="text" name="txtStaffCode"></td>
        </tr>
        <tr>
            <td>Name</td>
            <td><input type="text" name="txtStaffName"></td>
        </tr>
        <tr>
            <td>Contact</td>
            <td><input type="text" name="txtContact"></td>
        </tr>
        <tr>
            <td>Gender</td>
            <td>
                <input type="radio" name="rdbGender" value="Male">Male
                <input type="radio" name="rdbGender" value="FeMale">FeMale
            </td>
        </tr>
        <tr>
            <td>Email</td>
            <td><input type="email" name="txtEmail"></td>
        </tr>
        <tr>
            <td>Designation</td>
            <td>
                <select name="slctDesignation" id="slctDesignation">
                    <option>---Select---</option>
                    
                    {% for DesignationData in ServiceDesignations %}
                    
                    <option value="{{ DesignationData.id }}">{{ DesignationData.service_designation }}</option>
                    
                    {% endfor %}
                
                </select>
            </td>
        </tr>
     
       
        <tr>
            <td>Photo</td>
            <td><input type="file" name="fileStaffPhoto" id="fileStaffPhoto"></td>
        </tr>
        <tr>
            <td>User name</td>
            <td><input type="text" name="txtUsername" id="txtUsername"></td>
        </tr>
        <tr>
            <td>Password</td>
            <td><input type="text" name="txtPassword" id="txtPassword"></td>
        </tr>

     
        <tr>
            <td colspan="2"><input type="submit" value="Register Now"></td>
        </tr>
    </table>
    {{Message}}
    </form>



   














</body>
</html>

Hospital/templates/Hospital/ViewDailyService.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table border="1" align="center" cellpadding="10" style="border-collapse:collapse;">
        {% csrf_token %}
        <tr>
            <td>Service Code</td>
            <td>{{ ServiceCode  }}</td>
        </tr>
        <tr>
            <td>Service Type</td>
            <td>{{ ServiceType }}</td>
        </tr>
        <tr>
            <td>Service Rate</td>
            <td>{{ ServiceRate }}</td>
        </tr>
        <tr>
            <td>Description</td>
            <td>{{ Description }}</td>
        </tr>
        <tr>
            <td>Facilities</td>
            <td>{{Facilities}}</td>
        </tr>
        <tr>
            <td>KM Rate</td>
            <td>{{ KMRate }}</td>
        </tr>
    </table>
</body>
</html>

Hospital/templates/Hospital/ViewPackages.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table border="1" align="center" cellpadding="10" style="border-collapse:collapse;">
     
        <tr>
            <td>Package Code</td>
            <td>{{ PackageCode  }}</td>
        </tr>
        <tr>
            <td>Package Type</td>
            <td>{{ PackageType }}</td>
        </tr>
        <tr>
            <td>Package Rate</td>
            <td>{{ PackageRate }}</td>
        </tr>
        <tr>
            <td>Duration</td>
            <td>{{ Duration }}</td>
        </tr>
        <tr>
            <td>Facilities</td>
            <td>{{Facilities}}</td>
        </tr>
        <tr>
            <td>KM Rate</td>
            <td>{{ KMRate }}</td>
        </tr>
    </table>
</body>
</html>

Hospital/templates/Hospital/ViewProfile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table border="1" align="center" cellpadding="10" style="border-collapse:collapse;">
        <tr>
            <td colspan="2">
                <img src="{{HopitalImage.url}}" width="120" height="120">
            </td>
        </tr>
        <tr>
            <td>Name</td>
            <td>{{ HospitalName  }}</td>
        </tr>
        <tr>
            <td>Contact</td>
            <td>{{ HospitalContact }}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>{{ HospitalEmail }}</td>
        </tr>
        <tr>
            <td>Address</td>
            <td>{{ HospitalAddress }}</td>
        </tr>
        <tr>
            <td>District</td>
            <td>{{HospitalDistrict}}</td>
        </tr>
        <tr>
            <td>Place</td>
            <td>{{ HospitalPlace }}</td>
        </tr>
    </table>
</body>
</html>

Hospital/templates/Hospital/ViewStaffs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table border="1" align="center" cellpadding="10" style="border-collapse:collapse;">
        <tr>
            <td colspan="2">
                <img src="{{StaffImage.url}}" width="90" height="100">
            </td>
        </tr>
        <tr>
            <td>Staff Code</td>
            <td>{{ StaffCode  }}</td>
        </tr>
        <tr>
            <td>Name</td>
            <td>{{ Name }}</td>
        </tr>
        <tr>
            <td>Contact</td>
            <td>{{ Contact }}</td>
        </tr>
        <tr>
            <td>Gender</td>
            <td>{{ Gender }}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>{{ Email }}</td>
        </tr>
        <tr>
            <td>Designation</td>
            <td>{{ Designation }}</td>
        </tr>
    </table>
</body>
</html>

Hospital/templates/Hospital/ViewUsersComplaints.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table align="center" border="1" cellpadding="10" style="border-collapse: collapse;">
        <tr>
            <th>User Name</th>
            <th>Complaint Type</th>
            <th>Content</th>
            <th>Date</th>
            <th>Reply</th>
        </tr>
        {% for Data in usersComplaints %}
        <tr>
            <td>{{ Data.ucomplaint_user }}</td>
            <td>{{ Data.ucomplaint_type }}</td>
            <td>{{ Data.ucomplaint_content }}</td>
            <td>{{ Data.ucomplaint_date }}</td>
            <td colspan="2">
                <input type="text" name="uReply" />
            </td>
        </tr>
        {% endfor %}
    </table>
    <br>
    <div style="text-align: center;">
        <button>Submit</button>
    </div>
</body>
</html>